/***************
  GAME SPRITES
***************/

/* Apple Sprite */
const uint16_t apple_sprite[100] = {
  BLACK, BLACK, BLACK, BROWN, BLACK, DARK_GREEN, DARK_GREEN, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, BLACK, BROWN, DARK_GREEN, DARK_GREEN, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, BLACK, BROWN, BLACK, BLACK, BLACK, BLACK, BLACK,
  BLACK, RED, RED, BLACK, BROWN, BLACK, RED, RED, BLACK, BLACK,
  RED, RED, RED, RED, RED, RED, RED, BURLY_WOOD, BURLY_WOOD, BLACK,
  RED, RED, RED, RED, RED, RED, RED, RED, BURLY_WOOD, BLACK,
  RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK,
  RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK,
  BLACK, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK,
  BLACK, BLACK, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK
};

/* Mushroom Sprite */
const uint16_t shroom_sprite[100] = {
  BLACK, BLACK, DARK_RED, DARK_RED, BURLY_WOOD, DARK_RED, DARK_RED, DARK_RED, BLACK, BLACK,
  BLACK, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, BLACK,
  DARK_RED, DARK_RED, BURLY_WOOD, DARK_RED, DARK_RED, DARK_RED, BURLY_WOOD, DARK_RED, DARK_RED, DARK_RED,
  DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, BURLY_WOOD,
  BURLY_WOOD, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED,
  DARK_RED, DARK_RED, DARK_RED, DARK_RED, BURLY_WOOD, DARK_RED, DARK_RED, BURLY_WOOD, DARK_RED, DARK_RED,
  BLACK, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, DARK_RED, BLACK,
  BLACK, BLACK, BLACK, SADDLE_BROWN, SADDLE_BROWN, SADDLE_BROWN, SADDLE_BROWN, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, SADDLE_BROWN, SADDLE_BROWN, SADDLE_BROWN, SADDLE_BROWN, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK
};

/* Snake Head Sprite */
const uint16_t snake_head_sprite[100] = {
  BLACK, BLACK, BLACK, RED, BLACK, BLACK, RED, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, BLACK, RED, RED, BLACK, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, BLACK, RED, RED, BLACK, BLACK, BLACK, BLACK,
  BLACK, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, BLACK,
  BLACK, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLACK,
  ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
  ORANGE, ORANGE, BLACK, ORANGE, ORANGE, ORANGE, ORANGE, BLACK, ORANGE, ORANGE,
  ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
  ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE,
  ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE
};

