
/* Apple Sprite */
const uint16_t apple_sprite[100] = {
  BLACK, BLACK, BLACK, BROWN, BLACK, DARK_GREEN, DARK_GREEN, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, BLACK, BROWN, DARK_GREEN, DARK_GREEN, BLACK, BLACK, BLACK,
  BLACK, BLACK, BLACK, BLACK, BROWN, BLACK, BLACK, BLACK, BLACK, BLACK,
  BLACK, RED, RED, BLACK, BROWN, BLACK, RED, RED, BLACK, BLACK,
  RED, RED, RED, RED, RED, RED, RED, WHITE, WHITE, BLACK,
  RED, RED, RED, RED, RED, RED, RED, RED, WHITE, BLACK,
  RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK,
  RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK,
  BLACK, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK,
  BLACK, BLACK, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK
};
